### PR TITLE
fix(useFocusTrap): preserve sequential tab order when initially focused element is overridden

### LINKED ISSUE #482: Passing `AModal` an element to set initial focus to does not preserve tab order
**Describe the bug**

**To Reproduce**

1. Go to any playground on the Magna React Docs site
2. Paste the following snippet into the playground code editor:
    ```javascript
    () => {
      const initialFocusElementRef = useRef();
      const [open, setOpen] = useState(false);
      const ref = useRef();
      usePopupQuickExit({
        popupRef: ref,
        isEnabled: open,
        onExit: () => setOpen(false),
      });
      return (
        <>
          <AButton onClick={() => setOpen(true)}>Open</AButton>
          <AModal
            autoFocusElementRef={initialFocusElementRef}
            aria-labelledby="modal-title"
            isOpen={open}
          >
            <APanel ref={ref} style={{ width: "500px" }}>
              <APanelHeader>
                <APanelTitle id="modal-content">Demo</APanelTitle>
                <AButton
                  aria-label="Close form"
                  onClick={() => setOpen(false)}
                  tertiaryAlt
                  icon
                >
                  <AIcon>close</AIcon>
                </AButton>
              </APanelHeader>
              <APanelBody>
                <div className="mb-2">
                  <label>
                    Input #1
                    <input type="text" />
                  </label>
                </div>

                <div className="mb-2">
                  <label>
                    Input #2
                    <input type="text" />
                  </label>
                </div>

                <div className="mb-2">
                  <label>
                    Input #3
                    <input ref={initialFocusElementRef} type="text" />
                  </label>
                </div>

                <div className="mb-2">
                  <label>
                    Input #4
                    <input type="text" />
                  </label>
                </div>
              </APanelBody>
            </APanel>
          </AModal>
        </>
      );
    };
    ```
3. Open the modal
4. Observe that focus is on the third input from the top
5. Press `tab`
6. Observe that focus is set back to the modal button

**Expected behavior**

The tab order should remain intact when an element is passed to

### LINKED ISSUE #486: Clicking a focusable element inside of `AModal` does not preserve tab order
**Describe the bug**

**To Reproduce**

1. Go to any playground on the Magna React Docs site
2. Paste the following snippet into the playground code editor:
    ```javascript
    () => {
      const [open, setOpen] = useState(false);
      const ref = useRef();
      usePopupQuickExit({
        popupRef: ref,
        isEnabled: open,
        onExit: () => setOpen(false),
      });
      return (
        <>
          <AButton onClick={() => setOpen(true)}>Open</AButton>
          <AModal
            aria-labelledby="modal-title"
            isOpen={open}
          >
            <APanel ref={ref} style={{ width: "500px" }}>
              <APanelHeader>
                <APanelTitle id="modal-content">Demo</APanelTitle>
                <AButton
                  aria-label="Close form"
                  onClick={() => setOpen(false)}
                  tertiaryAlt
                  icon
                >
                  <AIcon>close</AIcon>
                </AButton>
              </APanelHeader>
              <APanelBody>
                <div className="mb-2">
                  <label>
                    Input #1
                    <input type="text" />
                  </label>
                </div>

                <div className="mb-2">
                  <label>
                    Input #2
                    <input type="text" />
                  </label>
                </div>

                <div className="mb-2">
                  <label>
                    Input #3
                    <input type="text" />
                  </label>
                </div>

                <div className="mb-2">
                  <label>
                    Input #4
                    <input type="text" />
                  </label>
                </div>
              </APanelBody>
            </APanel>
          </AModal>
        </>
      );
    };
    ```
3. Open the modal
4. Click the third input
5. Press `Tab`
6. Observe that focus is set back to the modal button
7. Press `Tab`
8. Observe that the focus is on the first input item

**Expected behavior**
When clicking an input within `AModal`, the tab order should respect the active element within the modal, i.e., the fourth input from the code snippet above should receive the next tab focus.

### PR DESCRIPTION
**Pull request by brennarvo**
* Closes #482 
* Closes #486

**What kind of change does this PR introduce?** 

This preserves sequential tab order for components calling `useFocusTrap` with an override on the element that should be initially focused to.

**What is the current behavior?** 
When a developer passes an element to set initial focus to within the focus trap, the tab order gets reset to the beginning of the trap on the next sequent `Tab` keydown.

**What is the new behavior (if this is a feature change)?**
Preserves tab order in situations where a developer passes `null` or a React ref to the `autoFocusElementRef`

**Does this PR introduce a breaking change?** 
No

### CODE REVIEW

File: framework/hooks/useFocusTrap/useFocusTrap.js [hunk 1]
```diff
@@ -37,35 +37,59 @@ export default function useFocusTrap({
...
+
+          initialFocusNode.focus({
             focusVisible: true
-          })
-        );
+          });
+
+          // Point the `TreeWalker` instance's active node to the one the developer
+          // passed in order to preserver tab order within the trap.
+          treeWalker.currentNode = initialFocusNode;
```
Comment (brennarvo) [inline framework/hooks/useFocusTrap/useFocusTrap.js:75]: This section of the conditional covers a situation like:

```jsx
const focusTrapContainerRef = useRef();
const initiallyFocusedElementRef = useRef();

useFocusTrap({
  rootRef: focusTrapContainerRef,
  autoFocusElementRef: initiallyFocusedElementRef,
});

return (
  <div ref={focusTrapContainerRef}>
    <a>Link #1</a>

    <a ref={initiallyFocusedElementRef}>Link #2</a>

    <a>Link #3</a>
  </div>
);
```

File: framework/hooks/useFocusTrap/useFocusTrap.js [hunk 2]
```diff
@@ -37,35 +37,59 @@ export default function useFocusTrap({
...
+        rootRef?.current.contains(document.activeElement) &&
+        canNodeReceiveFocus(document?.activeElement) ===
+          NodeFilter.FILTER_ACCEPT
+      ) {
+        // This covers the situation when a developer passes `autoFocusElement` as a
+        // falsy value to prevent `useFocusTrap` from stealing initial focus from any
+        // externally defined focus logic, e.g., an `autofocus` attribute on an element.
+        // Point the `TreeWalker` instance's active node to one that was externally
+        // focused to within the trap, e.g., one with an `autofocus` attribute.
+        treeWalker.currentNode = document.activeElement;
```
Comment (brennarvo) [inline framework/hooks/useFocusTrap/useFocusTrap.js:87]: const focusTrapContainerRef = useRef();

useFocusTrap({
  rootRef: focusTrapContainerRef,
  autoFocusElementRef: null, // Don't do any initial focus logic; let me handle that
});

return (
  <div ref={focusTrapContainerRef}>
    <button>Cancel</button>

    <form>
      <label>
        <input autofocus />
      </label>

      <button>Submit</button>
    </form>
  </div>
);

**Comment by brennarvo** [comment]
Forgot to cover another edge case. Labeling as "not ready" for now.

File: framework/hooks/useFocusTrap/useFocusTrap.js [hunk 3]
```diff
@@ -37,35 +41,79 @@ export default function useFocusTrap({
...
+        return NodeFilter.FILTER_ACCEPT;
+      } else {
+        return NodeFilter.FILTER_SKIP;
+      }
+    },
+    [rootRef]
+  );
+
   useEffect(() => {
+    let trapContainerEl;
```
Comment (brennarvo) [inline framework/hooks/useFocusTrap/useFocusTrap.js:56]: `eslint` gave me a helpful warning that I needed to define `rootRef.current` in a variable inside the `useEffect` scope since by the time the event listener is removed on line 112, the `current` property of the React ref will have likely changed.

**Comment by brennarvo** [comment]
Ready for review again.

**Review by rwharrisjr — APPROVED** [review]
nice. Tabbing is much more intuitive now
