### PR TITLE
Fix tooltip for multiselect counter

### LINKED ISSUE #573: Multi-selects that utilize template is buggy/not working
As reported by @radesai21, Using templates with Multiselect is no longer working.

Problems include:
1) It no longer selects: http://localhost:8001/components/multiselect#menu-item-templates
2) It does not list the items in the tooltip when selected with counter or display text in tags when `withTags` are used.
```
() => {
  const items = [
    {id: 1, name: "Bread, Cereal, Rice, and Pasta"},
    {id: 2, name: "Vegetables"},
    {id: 3, name: "Fruit", selected: true},
    {id: 4, name: "Milk, Yogurt, and Cheese"},
    {id: 5, name: "Meat, Poultry, Fish", disabled: true},
    {id: 6, name: "Fats, Oils, and Sweets"}
  ];
  
  const [value1, setValue1] = useState([{id: 1, name: "Bread, Cereal, Rice, and Pasta"}]);
  
  return (
    <div style={{minHeight: 220, minWidth: 250, marginRight: 20}}>
      <h3>MultiSelect with Objects</h3>
      <AMultiSelect
        label="Food Group"
        items={items}
        itemValue="id"
        itemText="name"
        placeholder="Pick a Food Group"
        onSelected={(newValue) => {
          alert(newValue);
          setValue1(newValue);
        }}
        itemTemplate={({ item, onClick }) => (
          <AListItem key={item.id} onClick={onClick}>
              {item.name}
          </AListItem>
        )}
        value={value1}
        itemText="name"
      />
    </div>
  );
} 
```

### PR DESCRIPTION
**Pull request by rwharrisjr**
Closes #573

### CODE REVIEW

File: framework/components/AMultiSelect/AMultiSelect.js [hunk 1]
```diff
@@ -314,7 +314,7 @@ const AMultiSelect = forwardRef(
       onKeyDown,
       placeholder: withTags
         ? value && !value.length
-          ? placeholder
+          ? placeholder || label
           : ""
         : label,
```
Comment (androche) [inline framework/components/AMultiSelect/AMultiSelect.js:319]: This needs to be moved to line 319 

```
placeholder: withTags
        ? value && !value.length
          ? placeholder
          : ""
        : placeholder || label
```

**Review by androche — CHANGES_REQUESTED** [review]

File: framework/components/AMultiSelect/AMultiSelect.js [hunk 2]
```diff
@@ -314,9 +314,9 @@ const AMultiSelect = forwardRef(
       onKeyDown,
       placeholder: withTags
         ? value && !value.length
-          ? placeholder
```
Comment (androche) [inline framework/components/AMultiSelect/AMultiSelect.js:317]: This should be put back to placeholder

**Review by androche — APPROVED** [review]
Tested on deployment, Raj has verified as well
