### PR TITLE
fix-627 Add accessibility features to modals and drawers

### LINKED ISSUE #627: [Accessibility] Modals and Drawers don't keep focus placement on close
When a user clicks on an element which opens either `AModal` or `ADrawer` components, the focus should return to that initial element upon closing said modal or drawer. Instead, the user must tab all the way from the start of the page to get back to where they were.

Open a Modal or Drawer, then close it and hit tab to see that the focus is at the top of the page. 

**Expected behavior**
Closing a modal or drawer should place the focus back on the element used to open them. It's outlined here in this example under "End of the Road!" section -
https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/dialog/

### PR DESCRIPTION
**Pull request by meggettt**
**Please check if the PR fulfills these requirements**
- [ ] The commit message follows semantic commit message guidelines
- [ ] The changes are documented in component docs and changelog
- [ ] The ESLint plugin has been updated if a new component is added
- [ ] Test have been added or modified, if appropriate
- [ ] Has been verified locally
- [ ] The component should accept a class name as a prop, if appropriate
- [ ] The component should accept a forward ref, if appropriate

**What kind of change does this PR introduce?** 

Closes  #627 

**What is the current behavior?** 
The current behavior is outlined in the issue here - #627 

**What is the new behavior (if this is a feature change)?**
When closing modals and drawers, the focus should return to whatever element was used to them. Also, they should be able to be closed upon pressing the "Escape" key, provided that an "onClose" function is passed into their props. The usePopupQuickExit hook is utilized to give these components this ability out of the box. 

**Does this PR introduce a breaking change?** 
Although not a breaking change, an onClose function to both Modals and Drawers. 

**Other information**:

### CODE REVIEW

File: framework/components/AModal/AModal.js [hunk 1]
```diff
@@ -298,9 +310,16 @@ You should provide either an \`aria-label\` or \`aria-labelledby\` prop to \`${c
...
    * If not using the `usePopupQuickExit` hook, pass in a function to handle clicking outside of the modal event. `withOverlay` prop must be set to true.
+   * @deprecated use "closeOnOutsideClick" in conjunction with a passed in "onClose" function to close modal
    */
   onClickOutside: PropTypes.func,
 
+  /**
+   * Function which closes the Modal. It is necessary for accessibility concerns, 
+   * specifically to enable exiting the Modal upon pressing the "Escape" key.
+   */
+  onClose: PropTypes.func,
```
Comment (rwharrisjr) [inline framework/components/AModal/AModal.js:321]: Might consider making this required, since that'll help enforce accessibility.

File: framework/components/AModal/AModal.js [hunk 2]
```diff
@@ -39,11 +40,13 @@ const AModal = forwardRef(
       delayUnmount = 200,
       children,
       isOpen: propsIsOpen,
+      onClose,
       small,
       medium,
       large,
       xlarge,
-      onClickOutside,
+      onClickOutside, //***DEPRECATED***
```
Comment (rwharrisjr) [inline framework/components/AModal/AModal.js:48]: since the function isn't used anymore, it might be better to remove it entirely and put in a warning

```
if (onClickOutside) {
console.warn("onClickOutside has been removed. Use onClose and set closeOnOutsideClick to true") 
}
```

If we make `onClose` required as well, this would add a bit more guidance to help people update

File: framework/components/AModal/AModal.mdx [hunk 3]
```diff
@@ -16,26 +16,26 @@ import {AModal} from "@cisco-sbg-ui/magna-react";
 
 ## Usage
 
+<AAlert className="mb-2" level="info" dismissable={false}>
+  Please provide an "onClose" function for accessibility concerns, specifically to enable exiting
```
Comment (rwharrisjr) [inline framework/components/AModal/AModal.mdx:20]: If we make `onClose` required, can remove the "please" :)

**Review by rwharrisjr — CHANGES_REQUESTED** [review]
A few changes.

Also appears to be failing the cypress tests

**Review by rwharrisjr — APPROVED** [review]
lgtm!
