### PR TITLE
Check if focus is in an input element before trapping arrow keys

### LINKED ISSUE #658: Cursor does not move when using right arrow key when `ATextInput` is nested inside of `AListItem`
**Describe the bug**

When `ATextInput` is nested inside of a `AListItem`, the right arrow key to move the cursor stops working.

**To Reproduce**

1. Go to a Playground editor on the docs site, e.g. https://magna-react.vercel.app/components/list#usage
2. Paste the following into the code playground:
    ```
    <AList>
      <AListItem>
        <ATextInput />
      </AListItem>
    </AList>
    ```
3. Type "Hello world" into the text input
4. Press your left arrow key
5. Press your right arrow key
6. **Observe that the cursor stays put**

**Expected behavior**

The cursor should move back to the original position when pressing the right arrow key.

**Environment (please complete the following information):**
 - Device: Desktop
 - OS: macOS
 - Browser Chrome
 - Version 122.0.6261.94

### PR DESCRIPTION
**Pull request by rwharrisjr**
Resolves #658

### CODE REVIEW

File: framework/components/AMenu/AMenu.js [hunk 1]
```diff
@@ -94,9 +94,15 @@ const AMenu = forwardRef(
         e.stopPropagation();
         const previous = getPrevious();
         previous && previous.focus();
-      } else if (e.keyCode === keyCodes.right) {
+      } else if (
+        e.keyCode === keyCodes.right &&
+        document.activeElement.tagName !== "INPUT"
```
Comment (brennarvo) [inline framework/components/AMenu/AMenu.js:99]: How would you feel about linking the issue that inspired this condition as a comment above it? Not required, but might add some context since arrow key logic is always finicky

Comment (brennarvo) [reply framework/components/AMenu/AMenu.js:99]: Actually, that's what git is for.

Comment (brennarvo) [reply framework/components/AMenu/AMenu.js:99]: Okay — last comment haha. Did you also mean to add this check for the `tagName` in the `AListItem` component, too?

https://github.com/cisco-sbg-ui/magna-react/blob/5d1cb8877c793acf49bcb5d86cade4b873d090ab/framework/components/AList/AListItem.js#L81-L99

**Review by brennarvo — APPROVED** [review]

**Review by androche — APPROVED** [review]
Pulled and tested
