### PR TITLE
#133 - check target in onClickOutside for AModal

### LINKED ISSUE #133: AModal onClickOutside closes modal when clicking inside the modal
**Describe the bug**

When using the `onClickOutside` prop, the modal closes when clicking the content inside of it. This can even be seen in the `AModal` demo for `onClickOutside` : https://magna-react.vercel.app/components/modal#usage

When trying to use the `usePopupQuickExit` instead, I found that `usePopupQuickExit` only works when the button is inside the same component as `AModal`. 

`usePopupQuickExit` also seemed to close when clicking the Edit buttons to open a markdown component in another modal we have.

**Steps to replicate**

To replicate these issues, you could pull down incident-manager and modify the 2 modals I changed in this PR: https://github.com/advthreat/incident-manager/pull/294

You can modify the `DeleteModal` to see `usePopupQuickExit` won't open the modal when the click action happens from a component outside of it (it just jolts the page).

And to see the `usePopupQuickExit` closing when clicking a button to change the markdown edit state, you can try using it in the `LongDescriptionDialog` component.

Both components will show `onClickOutside` close the modal when clicking inside of it, as it also shows this in the magna demo.

### PR DESCRIPTION
**Pull request by rwharrisjr**
Resolves #133

### CODE REVIEW

File: framework/components/AModal/AModal.js [hunk 1]
```diff
@@ -65,7 +66,18 @@ const AModal = forwardRef(
 
     if (withOverlay) {
       return ReactDOM.createPortal(
-        <APageOverlay className={visibilityClass} onClick={onClickOutside}>
+        <APageOverlay
+          ref={_overlayRef}
```
Comment (brennarvo) [inline framework/components/AModal/AModal.js:70]: `_overlayRef` is unused; let's remove it

**Review by brennarvo — CHANGES_REQUESTED** [review]

**Review by brennarvo — APPROVED** [review]
